
spring:
  data:
    cassandra:
      keyspace-name: main
      username: clXpTgGrKhaIlNtOOjRMFslT
      password: _cmB+KRyr-E9HwRdwTJZq7BInaAT47ygfLmwh7768REQfabFUriu7bN9SAspyAByAO7A0kRTELxXcp2wNKviKaMWhTg6AnuW5ogrXyjZMsnA.FhAk0.2S049rx,D1ObR
      schema-action: recreate-drop-unused
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s
  application:
    name: inbox-app
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Iv1.430c9220c8689f96
            client-secret: f32c14cbf72362c93a927bb88bb20172a64dfd1f

datastax.astra:
  secure-connect-bundle: secure-connect.zip

astra:
  db:
    id: 8ad8da9a-298b-4345-990d-04f5d49109a3
    region: asia-south1
    keyspace: main
    application:
      token: AstraCS:clXpTgGrKhaIlNtOOjRMFslT:851c85d505c91bbbfc7f3ab571311167a9679a480fc6938a194a340d566b647e
